name: Publish to npm
on:
  push:
    tags:
      - "*"


jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            # Setup .npmrc file to publish to npm
            - uses: actions/setup-node@v2
              with:
                  node-version: "17.x"
                  registry-url: "https://registry.npmjs.org"
                  # Defaults to the user or organization that owns the workflow file
                  scope: "@nuggxyz"
            - run: npm version from-git
            - run: node -p -e '`PACKAGE_VERSION=v${require("./package.json").version}`' >> $GITHUB_ENV
            - run: yarn
            # - run: yarn build
            - run: yarn publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_KEY }}
            # create release
            - uses: "marvinpinto/action-automatic-releases@latest"
              with:
                repo_token: "${{ secrets.GITHUB_TOKEN }}"
                prerelease: true
                automatic_release_tag: "latest"
                title: ${{ env.PACKAGE_VERSION }}
                files: |
                    LICENSE
                    *.tmLanguage.json






#${{ github.sha }}
