name: Publish to npm
on:
  push:
    branches:
      - "main"
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            # Setup .npmrc file to publish to npm
            - uses: actions/setup-node@v2
              with:
                  node-version: "17.x"
                  registry-url: "https://registry.npmjs.org"
                  # Defaults to the user or organization that owns the workflow file
                  scope: "@nuggxyz"
            -  uses:  'phips28/gh-action-bump-version@master'
               env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
               with:
                    minor-wording:  'MINOR'
                    major-wording:  'MAJOR'
                    tag-prefix:  'v'
                    default: patch
                    target-branch: 'main'
                    commit-message: 'CI: bump to {{version}} [skip ci]'
            - name: package-version
              run: node -p -e '`PACKAGE_VERSION=v${require("./package.json").version}`' >> $GITHUB_ENV
            - run: git pull && git checkout main && git reset --hard HEAD^ && git add . && git commit -m ${{ env.PACKAGE_VERSION }}
            - run: git push --force https://${process.env.GITHUB_ACTOR}:${process.env.GITHUB_TOKEN}@github.com/${process.env.GITHUB_REPOSITORY}.git
            - run: yarn
            # - run: yarn build
            - run: yarn publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_KEY }}
            - name: package-version
              run: node -p -e '`PACKAGE_VERSION=v${require("./package.json").version}`' >> $GITHUB_ENV
            # create release
            - uses: "marvinpinto/action-automatic-releases@latest"
              with:
                repo_token: "${{ secrets.GITHUB_TOKEN }}"
                prerelease: true
                automatic_release_tag: "latest"
                title: ${{ env.PACKAGE_VERSION }}
                files: |
                    LICENSE
                    *.tmLanguage.json




